class RankingModelClass {
  int no;
  String image;
  String title;
  String description_1;
  String description_2;
  String description_3;
  String description_4;
  String row1txt1;
  String row1txt2;
  String row1txt3;
  String row1txt4;
  String row2txt1;
  String row2txt2;
  String row2txt3;
  String row2txt4;

  RankingModelClass({
    required this.no,
    required this.image,
    required this.title,
    required this.description_1,
    required this.description_2,
    required this.description_3,
    required this.description_4,
    required this.row1txt1,
    required this.row1txt2,
    required this.row1txt3,
    required this.row1txt4,
    required this.row2txt1,
    required this.row2txt2,
    required this.row2txt3,
    required this.row2txt4,
  });

  static List<RankingModelClass> MODEL_2 = [
    RankingModelClass(
      no: 1,
      image: 'assets/Ranking/pic1.png',
      title: 'NFT Bored Bunny',
      description_1: '8K ',
      description_2: "Items",
      description_3: '4.5K ',
      description_4: 'Owners',
      row1txt1: '24h %',
      row1txt2: '7d %',
      row1txt3: 'Volume',
      row1txt4: 'Floor Price',
      row2txt1: '+32%',
      row2txt2: '+32%',
      row2txt3: '4.2 ETH',
      row2txt4: '4.2 ETH',
    ),
    RankingModelClass(
      no: 2,
      image: 'assets/Ranking/pic1.png',
      title: 'NFT Bored Bunny',
      description_1: '8K ',
      description_2: "Items",
      description_3: '4.5K ',
      description_4: 'Owners',
      row1txt1: '24h %',
      row1txt2: '7d %',
      row1txt3: 'Volume',
      row1txt4: 'Floor Price',
      row2txt1: '+32%',
      row2txt2: '+32%',
      row2txt3: '4.2 ETH',
      row2txt4: '4.2 ETH',
    ),
    RankingModelClass(
      no: 3,
      image: 'assets/Ranking/pic1.png',
      title: 'NFT Bored Bunny',
      description_1: '8K ',
      description_2: "Items",
      description_3: '4.5K ',
      description_4: 'Owners',
      row1txt1: '24h %',
      row1txt2: '7d %',
      row1txt3: 'Volume',
      row1txt4: 'Floor Price',
      row2txt1: '+32%',
      row2txt2: '+32%',
      row2txt3: '4.2 ETH',
      row2txt4: '4.2 ETH',
    ),
    RankingModelClass(
      no: 4,
      image: 'assets/Ranking/pic1.png',
      title: 'NFT Bored Bunny',
      description_1: '8K ',
      description_2: "Items",
      description_3: '4.5K ',
      description_4: 'Owners',
      row1txt1: '24h %',
      row1txt2: '7d %',
      row1txt3: 'Volume',
      row1txt4: 'Floor Price',
      row2txt1: '+32%',
      row2txt2: '+32%',
      row2txt3: '4.2 ETH',
      row2txt4: '4.2 ETH',
    ),
  ];
}
